version: "3.7"

services:

  app:
    build:
      args:
        user: matas
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ipfsexplorer
    container_name: ipfsexplorer-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ipfsexplorer

  mysql:
    image: mysql:8.0
    container_name: ipfsexplorer-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - ipfsexplorer

  nginx:
    image: nginx:alpine
    container_name: ipfsexplorer-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - ipfsexplorer

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    container_name: ipfsexplorer-phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - ipfsexplorer

networks:
  ipfsexplorer:
    driver: bridge
